pipeline {
    agent any

    stage('Conditionals') {
        steps {
            script {
                if (env.HOME == '/root') {
                    echo "Test path value is master"
                } else {
                    echo "Test path value is not master"
                }
            }
        }
    }
}
