pipeline {
	agent any

	stages {
		stage('Build') {
			agent {
				node {
					label 'node2'
				}
			}
			steps {
				echo 'Building...'
				echo 'Building more...'
				sleep 20
			}
		}
		stage('Test'){
			agent {
				node {
					label 'node1'
				}
			}
			steps {
				echo 'Testing...'
				build job: 'AbhiJ1', parameters: [[$class: 'StringParameterValue', name: 'target', value: target], [$class: 'BooleanParameterValue', name: 'update_composer', value: update_composer.toBoolean()]]
			}
		}
		stage('Deploy'){
			steps {
				echo 'Deploying...'
			}
		}
	}
}
